
spring.application.name=hotel-web
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Specific Pools Tuning
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=MyHikariCP
# Enable template caching (set to false for local development)
spring.thymeleaf.cache=true

# Template files location configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Encoding standard
spring.thymeleaf.encoding=UTF-8

server.port=8000